### ISSUE TITLE
Possible issue in how quoting for shell out

### ISSUE THREAD

**Issue by morgen-peschke** [gkulasik/grpc_assistant_server#10]
I think there’s a bug in how the grpc proxy handles quotation:
```
curl --location --request POST 'localhost:3000/service/Foo/execute/Bar.json' \
--header 'GRPC_META_import_path: ~/protos/src' \
--header 'GRPC_META_service_proto_path: foo.proto' \
--header 'GRPC_META_plaintext: true' \
--header 'GRPC_META_verbose: true' \
--header 'GRPC_META_server_address: host.docker.internal:9000' \
--header 'Content-Type: application/json' \
--data-raw '{
  "value": {
    "text": "Test'\''Last.Name"
  }
}'
```
Produces:
```
{
    "error": "sh: 1: Syntax error: Unterminated quoted string\n"
}
```

**Comment by gkulasik** [comment]
This is in fact a bug. I haven't been able to figure out a solution yet, most substitution in Ruby will cause too many backslashes for the Bash shell resulting in the same or different errors. 

I need to spend more time looking into this to figure out a work around, potentially passing in the body as a file or other input type rather than command line argument.

**Comment by morgen-peschke** [comment]
It might be worth trying pseudo-escaping, which doesn't use a backslash.

The short version is: 
1. Close the current `'` quoted string
2. Immediately open a new string using `"` instead of `'`
3. Add the single `'`
4. Close the current `"` quoted string
5. Open a new `'` quoted string for the rest of the input

If you put two strings back-to-back, `bash` will concatenate them, so it effectively escapes the singe quote, even though it isn't _technically_ escaping anything.

```bash
echo 'That'"'"'s odd looking'
```

This may or may not work, depending on how the arguments are passed to `curl` by `ruby`.
